### ISSUE TITLE
cannot install on linux

### ISSUE THREAD

**Issue by interfaith** [webuild-community/federated-blog#107]
og$ yarn
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
error Error: https://registry.yarnpkg.com/@moai/core/-/core-1.2.0.tgz: Request failed "404 Not Found"
    at ResponseError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/usr/local/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:66218:16)
    at Request.emit (node:events:513:28)
    at module.exports.Request.onRequestResponse (/usr/local/lib/node_modules/yarn/lib/cli.js:141751:10)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:695:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:536:22)
    at TLSSocket.emit (node:events:513:28)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this comma

**Comment by huytd** [comment]
Sorry but this error is caused by the `moaijs` package has been removed from NPM/Yarn.

I think the only way to solve this is to install `moai` from Github repo https://github.com/moaijs/moai but it's out of my time budget for now, PRs are welcomed.
